/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as GooglechatRouteImport } from './routes/googlechat'
import { Route as MattermostRouteImport } from './routes/mattermost'
import { Route as OpsgenieRouteImport } from './routes/opsgenie'
import { Route as PagerdutyRouteImport } from './routes/pagerduty'
import { Route as SendRouteImport } from './routes/send'
import { Route as SinksRouteImport } from './routes/sinks'
import { Route as SlackRouteImport } from './routes/slack'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as DiscordChannelIdRouteImport } from './routes/discord.$channelId'
import { Route as GooglechatChannelIdRouteImport } from './routes/googlechat.$channelId'
import { Route as MattermostChannelIdRouteImport } from './routes/mattermost.$channelId'
import { Route as OpsgenieChannelIdRouteImport } from './routes/opsgenie.$channelId'
import { Route as PagerdutyChannelIdRouteImport } from './routes/pagerduty.$channelId'
import { Route as SlackChannelIdRouteImport } from './routes/slack.$channelId'
import { Route as TeamsChannelIdRouteImport } from './routes/teams.$channelId'
import { Route as TelegramChannelIdRouteImport } from './routes/telegram.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglechatRoute = GooglechatRouteImport.update({
  id: '/googlechat',
  path: '/googlechat',
  getParentRoute: () => rootRouteImport,
} as any)
const MattermostRoute = MattermostRouteImport.update({
  id: '/mattermost',
  path: '/mattermost',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsgenieRoute = OpsgenieRouteImport.update({
  id: '/opsgenie',
  path: '/opsgenie',
  getParentRoute: () => rootRouteImport,
} as any)
const PagerdutyRoute = PagerdutyRouteImport.update({
  id: '/pagerduty',
  path: '/pagerduty',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SinksRoute = SinksRouteImport.update({
  id: '/sinks',
  path: '/sinks',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackRoute = SlackRouteImport.update({
  id: '/slack',
  path: '/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordChannelIdRoute = DiscordChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => DiscordRoute,
} as any)
const GooglechatChannelIdRoute = GooglechatChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => GooglechatRoute,
} as any)
const MattermostChannelIdRoute = MattermostChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => MattermostRoute,
} as any)
const OpsgenieChannelIdRoute = OpsgenieChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => OpsgenieRoute,
} as any)
const PagerdutyChannelIdRoute = PagerdutyChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => PagerdutyRoute,
} as any)
const SlackChannelIdRoute = SlackChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => SlackRoute,
} as any)
const TeamsChannelIdRoute = TeamsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => TeamsRoute,
} as any)
const TelegramChannelIdRoute = TelegramChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => TelegramRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discord': typeof DiscordRouteWithChildren
  '/fixtures': typeof FixturesRoute
  '/googlechat': typeof GooglechatRouteWithChildren
  '/mattermost': typeof MattermostRouteWithChildren
  '/opsgenie': typeof OpsgenieRouteWithChildren
  '/pagerduty': typeof PagerdutyRouteWithChildren
  '/send': typeof SendRoute
  '/sinks': typeof SinksRoute
  '/slack': typeof SlackRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/telegram': typeof TelegramRouteWithChildren
  '/discord/$channelId': typeof DiscordChannelIdRoute
  '/googlechat/$channelId': typeof GooglechatChannelIdRoute
  '/mattermost/$channelId': typeof MattermostChannelIdRoute
  '/opsgenie/$channelId': typeof OpsgenieChannelIdRoute
  '/pagerduty/$channelId': typeof PagerdutyChannelIdRoute
  '/slack/$channelId': typeof SlackChannelIdRoute
  '/teams/$channelId': typeof TeamsChannelIdRoute
  '/telegram/$channelId': typeof TelegramChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discord': typeof DiscordRouteWithChildren
  '/fixtures': typeof FixturesRoute
  '/googlechat': typeof GooglechatRouteWithChildren
  '/mattermost': typeof MattermostRouteWithChildren
  '/opsgenie': typeof OpsgenieRouteWithChildren
  '/pagerduty': typeof PagerdutyRouteWithChildren
  '/send': typeof SendRoute
  '/sinks': typeof SinksRoute
  '/slack': typeof SlackRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/telegram': typeof TelegramRouteWithChildren
  '/discord/$channelId': typeof DiscordChannelIdRoute
  '/googlechat/$channelId': typeof GooglechatChannelIdRoute
  '/mattermost/$channelId': typeof MattermostChannelIdRoute
  '/opsgenie/$channelId': typeof OpsgenieChannelIdRoute
  '/pagerduty/$channelId': typeof PagerdutyChannelIdRoute
  '/slack/$channelId': typeof SlackChannelIdRoute
  '/teams/$channelId': typeof TeamsChannelIdRoute
  '/telegram/$channelId': typeof TelegramChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discord': typeof DiscordRouteWithChildren
  '/fixtures': typeof FixturesRoute
  '/googlechat': typeof GooglechatRouteWithChildren
  '/mattermost': typeof MattermostRouteWithChildren
  '/opsgenie': typeof OpsgenieRouteWithChildren
  '/pagerduty': typeof PagerdutyRouteWithChildren
  '/send': typeof SendRoute
  '/sinks': typeof SinksRoute
  '/slack': typeof SlackRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/telegram': typeof TelegramRouteWithChildren
  '/discord/$channelId': typeof DiscordChannelIdRoute
  '/googlechat/$channelId': typeof GooglechatChannelIdRoute
  '/mattermost/$channelId': typeof MattermostChannelIdRoute
  '/opsgenie/$channelId': typeof OpsgenieChannelIdRoute
  '/pagerduty/$channelId': typeof PagerdutyChannelIdRoute
  '/slack/$channelId': typeof SlackChannelIdRoute
  '/teams/$channelId': typeof TeamsChannelIdRoute
  '/telegram/$channelId': typeof TelegramChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discord'
    | '/fixtures'
    | '/googlechat'
    | '/mattermost'
    | '/opsgenie'
    | '/pagerduty'
    | '/send'
    | '/sinks'
    | '/slack'
    | '/teams'
    | '/telegram'
    | '/discord/$channelId'
    | '/googlechat/$channelId'
    | '/mattermost/$channelId'
    | '/opsgenie/$channelId'
    | '/pagerduty/$channelId'
    | '/slack/$channelId'
    | '/teams/$channelId'
    | '/telegram/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discord'
    | '/fixtures'
    | '/googlechat'
    | '/mattermost'
    | '/opsgenie'
    | '/pagerduty'
    | '/send'
    | '/sinks'
    | '/slack'
    | '/teams'
    | '/telegram'
    | '/discord/$channelId'
    | '/googlechat/$channelId'
    | '/mattermost/$channelId'
    | '/opsgenie/$channelId'
    | '/pagerduty/$channelId'
    | '/slack/$channelId'
    | '/teams/$channelId'
    | '/telegram/$channelId'
  id:
    | '__root__'
    | '/'
    | '/discord'
    | '/fixtures'
    | '/googlechat'
    | '/mattermost'
    | '/opsgenie'
    | '/pagerduty'
    | '/send'
    | '/sinks'
    | '/slack'
    | '/teams'
    | '/telegram'
    | '/discord/$channelId'
    | '/googlechat/$channelId'
    | '/mattermost/$channelId'
    | '/opsgenie/$channelId'
    | '/pagerduty/$channelId'
    | '/slack/$channelId'
    | '/teams/$channelId'
    | '/telegram/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscordRoute: typeof DiscordRouteWithChildren
  FixturesRoute: typeof FixturesRoute
  GooglechatRoute: typeof GooglechatRouteWithChildren
  MattermostRoute: typeof MattermostRouteWithChildren
  OpsgenieRoute: typeof OpsgenieRouteWithChildren
  PagerdutyRoute: typeof PagerdutyRouteWithChildren
  SendRoute: typeof SendRoute
  SinksRoute: typeof SinksRoute
  SlackRoute: typeof SlackRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  TelegramRoute: typeof TelegramRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googlechat': {
      id: '/googlechat'
      path: '/googlechat'
      fullPath: '/googlechat'
      preLoaderRoute: typeof GooglechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mattermost': {
      id: '/mattermost'
      path: '/mattermost'
      fullPath: '/mattermost'
      preLoaderRoute: typeof MattermostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opsgenie': {
      id: '/opsgenie'
      path: '/opsgenie'
      fullPath: '/opsgenie'
      preLoaderRoute: typeof OpsgenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagerduty': {
      id: '/pagerduty'
      path: '/pagerduty'
      fullPath: '/pagerduty'
      preLoaderRoute: typeof PagerdutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinks': {
      id: '/sinks'
      path: '/sinks'
      fullPath: '/sinks'
      preLoaderRoute: typeof SinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack': {
      id: '/slack'
      path: '/slack'
      fullPath: '/slack'
      preLoaderRoute: typeof SlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/$channelId': {
      id: '/discord/$channelId'
      path: '/$channelId'
      fullPath: '/discord/$channelId'
      preLoaderRoute: typeof DiscordChannelIdRouteImport
      parentRoute: typeof DiscordRoute
    }
    '/googlechat/$channelId': {
      id: '/googlechat/$channelId'
      path: '/$channelId'
      fullPath: '/googlechat/$channelId'
      preLoaderRoute: typeof GooglechatChannelIdRouteImport
      parentRoute: typeof GooglechatRoute
    }
    '/mattermost/$channelId': {
      id: '/mattermost/$channelId'
      path: '/$channelId'
      fullPath: '/mattermost/$channelId'
      preLoaderRoute: typeof MattermostChannelIdRouteImport
      parentRoute: typeof MattermostRoute
    }
    '/opsgenie/$channelId': {
      id: '/opsgenie/$channelId'
      path: '/$channelId'
      fullPath: '/opsgenie/$channelId'
      preLoaderRoute: typeof OpsgenieChannelIdRouteImport
      parentRoute: typeof OpsgenieRoute
    }
    '/pagerduty/$channelId': {
      id: '/pagerduty/$channelId'
      path: '/$channelId'
      fullPath: '/pagerduty/$channelId'
      preLoaderRoute: typeof PagerdutyChannelIdRouteImport
      parentRoute: typeof PagerdutyRoute
    }
    '/slack/$channelId': {
      id: '/slack/$channelId'
      path: '/$channelId'
      fullPath: '/slack/$channelId'
      preLoaderRoute: typeof SlackChannelIdRouteImport
      parentRoute: typeof SlackRoute
    }
    '/teams/$channelId': {
      id: '/teams/$channelId'
      path: '/$channelId'
      fullPath: '/teams/$channelId'
      preLoaderRoute: typeof TeamsChannelIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/telegram/$channelId': {
      id: '/telegram/$channelId'
      path: '/$channelId'
      fullPath: '/telegram/$channelId'
      preLoaderRoute: typeof TelegramChannelIdRouteImport
      parentRoute: typeof TelegramRoute
    }
  }
}

interface DiscordRouteChildren {
  DiscordChannelIdRoute: typeof DiscordChannelIdRoute
}

const DiscordRouteChildren: DiscordRouteChildren = {
  DiscordChannelIdRoute: DiscordChannelIdRoute,
}

const DiscordRouteWithChildren =
  DiscordRoute._addFileChildren(DiscordRouteChildren)

interface GooglechatRouteChildren {
  GooglechatChannelIdRoute: typeof GooglechatChannelIdRoute
}

const GooglechatRouteChildren: GooglechatRouteChildren = {
  GooglechatChannelIdRoute: GooglechatChannelIdRoute,
}

const GooglechatRouteWithChildren = GooglechatRoute._addFileChildren(
  GooglechatRouteChildren,
)

interface MattermostRouteChildren {
  MattermostChannelIdRoute: typeof MattermostChannelIdRoute
}

const MattermostRouteChildren: MattermostRouteChildren = {
  MattermostChannelIdRoute: MattermostChannelIdRoute,
}

const MattermostRouteWithChildren = MattermostRoute._addFileChildren(
  MattermostRouteChildren,
)

interface OpsgenieRouteChildren {
  OpsgenieChannelIdRoute: typeof OpsgenieChannelIdRoute
}

const OpsgenieRouteChildren: OpsgenieRouteChildren = {
  OpsgenieChannelIdRoute: OpsgenieChannelIdRoute,
}

const OpsgenieRouteWithChildren = OpsgenieRoute._addFileChildren(
  OpsgenieRouteChildren,
)

interface PagerdutyRouteChildren {
  PagerdutyChannelIdRoute: typeof PagerdutyChannelIdRoute
}

const PagerdutyRouteChildren: PagerdutyRouteChildren = {
  PagerdutyChannelIdRoute: PagerdutyChannelIdRoute,
}

const PagerdutyRouteWithChildren = PagerdutyRoute._addFileChildren(
  PagerdutyRouteChildren,
)

interface SlackRouteChildren {
  SlackChannelIdRoute: typeof SlackChannelIdRoute
}

const SlackRouteChildren: SlackRouteChildren = {
  SlackChannelIdRoute: SlackChannelIdRoute,
}

const SlackRouteWithChildren = SlackRoute._addFileChildren(SlackRouteChildren)

interface TeamsRouteChildren {
  TeamsChannelIdRoute: typeof TeamsChannelIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsChannelIdRoute: TeamsChannelIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TelegramRouteChildren {
  TelegramChannelIdRoute: typeof TelegramChannelIdRoute
}

const TelegramRouteChildren: TelegramRouteChildren = {
  TelegramChannelIdRoute: TelegramChannelIdRoute,
}

const TelegramRouteWithChildren = TelegramRoute._addFileChildren(
  TelegramRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscordRoute: DiscordRouteWithChildren,
  FixturesRoute: FixturesRoute,
  GooglechatRoute: GooglechatRouteWithChildren,
  MattermostRoute: MattermostRouteWithChildren,
  OpsgenieRoute: OpsgenieRouteWithChildren,
  PagerdutyRoute: PagerdutyRouteWithChildren,
  SendRoute: SendRoute,
  SinksRoute: SinksRoute,
  SlackRoute: SlackRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  TelegramRoute: TelegramRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
